PrefectVotingApplication/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PrefectVotingApplication.Areas.Identity.Data;
using PrefectVotingApplication.Models;

namespace PrefectVotingApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly PrefectVotingApplicationDbContext _context;
        private readonly UserManager<PrefectVotingApplicationUser> _userManager;

        public RolesController(PrefectVotingApplicationDbContext context, UserManager<PrefectVotingApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        private async Task LoadUserRoleAsync()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    var fullUser = await _context.Users
                        .Include(u => u.Role)
                        .FirstOrDefaultAsync(u => u.Id == user.Id);

                    ViewBag.RoleName = fullUser?.Role?.RoleName.ToString();
                }
            }
        }
        // GET: Roles
        public async Task<IActionResult> Index()
        {
            await LoadUserRoleAsync(); // load role before rendering view
            return View(await _context.Role.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Role
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        //public IActionResult Create()
        //{
        //    ViewBag.RoleNameList = new SelectList(Enum.GetValues(typeof(Role.RoleNames)));
        //    return View();
        //}

        //// POST: Roles/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("RoleId,RoleName,VoteWeight")] Role role)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        _context.Add(role);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewBag.RoleNameList = new SelectList(Enum.GetValues(typeof(Role.RoleNames)));
        //    return View(role);
        //} 
        //no new roles should be created

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Role.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,VoteWeight")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.RoleNameList = new SelectList(Enum.GetValues(typeof(Role.RoleNames)));
            return View(role);
        }

        //// GET: Roles/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var role = await _context.Role
        //        .FirstOrDefaultAsync(m => m.RoleId == id);
        //    if (role == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(role);
        //}

        //// POST: Roles/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var role = await _context.Role.FindAsync(id);
        //    if (role != null)
        //    {
        //        _context.Role.Remove(role);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool RoleExists(int id)
        {
            return _context.Role.Any(e => e.RoleId == id);
        }
    }
}

PrefectVotingApplication/Controllers/VotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PrefectVotingApplication.Areas.Identity.Data;
using PrefectVotingApplication.Models;
using Microsoft.AspNetCore.Identity;


namespace PrefectVotingApplication.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class VotesController : Controller
    {
        private readonly PrefectVotingApplicationDbContext _context;
        private readonly UserManager<PrefectVotingApplicationUser> _userManager;
        public VotesController(PrefectVotingApplicationDbContext context, UserManager<PrefectVotingApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        private async Task LoadUserRoleAsync()//since im using a lot of If statements to check for roles, i made this function to reduce redundancy
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                if (user != null)
                {
                    var fullUser = await _context.Users
                        .Include(u => u.Role)
                        .FirstOrDefaultAsync(u => u.Id == user.Id);

                    ViewBag.RoleName = fullUser?.Role?.RoleName.ToString();
                }
            }
        }
        // GET: Votes
        public async Task<IActionResult> Index(int? pageNumber, string sortOrder)
        {
            await LoadUserRoleAsync(); // load role before rendering view
            var prefectVotingApplicationDbContext = _context.Votes.Include(v => v.Receiver).Include(v => v.Voter);

          
            var votes = _context.Votes.Include(v => v.Receiver).Include(v => v.Voter).OrderByDescending(v => v.Timestamp); //this sorts by newest date/timestamp


            //pagination
            int pageSize = 16;
            int totalCount = await votes.CountAsync();
            int totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
            int currentPage = pageNumber ?? 1;

            var pageItems = await votes.Skip((currentPage - 1) * pageSize).Take(pageSize).ToListAsync();
            // pass data to view
            ViewData["PageNumber"] = currentPage;
            ViewData["TotalPages"] = totalPages;

            return View(pageItems);
            //return View(await prefectVotingApplicationDbContext.ToListAsync());
        }

        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> AllVotes(string searchString, int pageNumber = 1)
        {
            await LoadUserRoleAsync(); // load role before rendering view
            int pageSize = 16;

            // gets roles of both voter and receiver for filtering
            var votesQuery = _context.Votes
                .Include(v => v.Voter).ThenInclude(u => u.Role)
                .Include(v => v.Receiver).ThenInclude(u => u.Role).OrderByDescending(v => v.Timestamp).AsQueryable();

            // Only show votes where either the voter OR receiver is Student or Teacher
            votesQuery = votesQuery.Where(v =>
                (v.Voter.Role.RoleName == Role.RoleNames.Student || v.Voter.Role.RoleName == Role.RoleNames.Teacher) &&
                (v.Receiver.Role.RoleName == Role.RoleNames.Student || v.Receiver.Role.RoleName == Role.RoleNames.Teacher));

            if (!string.IsNullOrEmpty(searchString))
            {
                votesQuery = votesQuery.Where(v =>
                    v.Voter.FirstName.Contains(searchString) ||
                    v.Voter.LastName.Contains(searchString) ||
                    v.Receiver.FirstName.Contains(searchString) ||
                    v.Receiver.LastName.Contains(searchString));
            }

            var totalVotes = await votesQuery.CountAsync();
            var totalPages = (int)Math.Ceiling(totalVotes / (double)pageSize);

            var votes = await votesQuery
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            ViewData["PageNumber"] = pageNumber;
            ViewData["TotalPages"] = totalPages;
            ViewData["CurrentFilter"] = searchString;

            return View(votes);
        }

        // GET: Votes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var votes = await _context.Votes
                .Include(v => v.Receiver)
                .Include(v => v.Voter)
                .FirstOrDefaultAsync(m => m.VoteId == id);
            if (votes == null)
            {
                return NotFound();
            }

            return View(votes);
        }

        // GET: Votes/Create
        public IActionResult Create()
        {
            ViewData["ReceiverId"] = new SelectList(_context.User, "Id", "Id");
            ViewData["VoterId"] = new SelectList(_context.User, "Id", "Id");
            ViewBag.ElectionId = new SelectList(_context.Election, "ElectionId", "ElectionTitle");
            return View();
        }

        // POST: Votes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VoteId,VoterId,ReceiverId,ElectionId,Timestamp")] Votes votes)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(votes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ReceiverId"] = new SelectList(_context.User, "Id", "Id", votes.ReceiverId);
            ViewData["VoterId"] = new SelectList(_context.User, "Id", "Id", votes.VoterId);
            ViewBag.ElectionId = new SelectList(_context.Election, "ElectionId", "ElectionTitle");
            return View(votes);
        }

        // GET: Votes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var votes = await _context.Votes.FindAsync(id);
            if (votes == null)
            {
                return NotFound();
            }
            ViewData["ReceiverId"] = new SelectList(_context.User, "Id", "Id", votes.ReceiverId);
            ViewData["VoterId"] = new SelectList(_context.User, "Id", "Id", votes.VoterId);
            ViewBag.ElectionId = new SelectList(_context.Election, "ElectionId", "ElectionTitle");
            return View(votes);
        }

        // POST: Votes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Vote(string receiverId, string viewMode)
        {
            var voterEmail = User.Identity?.Name; //grabs user name(currently logged in)
            var voter = await _context.User.FirstOrDefaultAsync(u => u.Email == voterEmail);

            if (voter == null || string.IsNullOrEmpty(receiverId)) //if a user if not logged-in
            {
                TempData["Message"] = "Vote failed. Login first.";
                return RedirectToAction("Index", "PrefectVotingApplicationUsers", new { viewMode = viewMode ?? "grid" }); 
            }

            var activeElection = await _context.Election
                .FirstOrDefaultAsync(e => e.Status == Election.ElectionStatus.Active); //finds the one active election


            if (activeElection == null) // if there is no active election, then it will show this
            {
                TempData["Message"] = "Wait for Staff to start election.";
                return RedirectToAction("Index", "PrefectVotingApplicationUsers", new { viewMode = viewMode ?? "grid" });
            }

            // finds for duplicate voting for same receiver
            bool alreadyVoted = await _context.Votes
                .AnyAsync(v => v.VoterId == voter.Id && v.ReceiverId == receiverId && v.ElectionId == activeElection.ElectionId);

            if (alreadyVoted) // if user has already voted for the same prefect
            {
                TempData["Message"] = "You have already voted for this prefect.";
                return RedirectToAction("Index", "PrefectVotingApplicationUsers", new { viewMode = viewMode ?? "grid" });
            }

            // Check if user reached 60 vote limit
            int totalUserVotes = await _context.Votes
                .CountAsync(v => v.VoterId == voter.Id && v.ElectionId == activeElection.ElectionId);

            if (totalUserVotes >= 60) //if total votes is over 60 or is 60, it will give an error message instead of counting
            {
                TempData["Message"] = "You already have 60 votes.";
                return RedirectToAction("Index", "PrefectVotingApplicationUsers", new { viewMode = viewMode ?? "grid" });
            }


            var vote = new Votes
            {
                VoterId = voter.Id,
                ReceiverId = receiverId,
                ElectionId = activeElection.ElectionId,
                Timestamp = DateTime.Now
            };

            _context.Votes.Add(vote); 
            await _context.SaveChangesAsync();

            TempData["Message"] = "Vote successfully recorded!"; //if the if statements are passed or not gotten captured, then the vote is successful
            return RedirectToAction("Index", "PrefectVotingApplicationUsers", new { viewMode = viewMode ?? "grid" });
        }
        [HttpPost]

PrefectVotingApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PrefectVotingApplication.Areas.Identity.Data

<!DOCTYPE html>
<html lang="en">

@{
    var roleName = ViewBag.RoleName as string;
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrefectVotingApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrefectVotingApplication.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-black bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/AvCol Logo White on Black Landscape.png" alt="Home" style="height:50px; margin-right:10px;" /> 
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @* by default everyone can see the prefects/student page *@
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Index">Students</a>
                        </li> 
                        @if (roleName == "Student")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Votes" asp-action="YourVotes">Your Votes</a>
                            </li>
                        }
                        @if (roleName == "Teacher") //teachers can view only all the votes in the system so if they want to count manually
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Votes" asp-action="YourVotes">Your Votes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Votes" asp-action="AllVotes">All Votes</a>
                        </li>}

                        @if (roleName == "Staff") //school staff can see all votes and make elections (admin role is also considered staff)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Votes" asp-action="YourVotes">Your Votes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Votes" asp-action="AllVotes">All Votes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Election" asp-action="Index">Election(Year)</a>
                            </li>
                        }
                        
                        
                        @if (User.IsInRole("Admin")) // admin can see everything
                        {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Votes" asp-action="Index">VotesLog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area=""  asp-controller="Votes" asp-action="TopStudents">Top 60</a>
                        </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial.cshtml" />
            </div>
        </nav>
    </header>
    @if (ViewData["Title"]?.ToString() == "Home Page")//homepage code is here
    {
        <div class="fullscreen-section section1">
            <div class="overlay"></div>
                <div class="content hero-content text-center">
                    <p class="hero-small">Welcome to Avondale College</p>
                    <h1 class="hero-title">Prefect Voting @DateTime.Now.Year</h1> @* gets the current year and only the year and displays it: 2025 *@
                    <p class="hero-subtitle">Empowering Students, Shaping Leaders</p>
                    <div class="hero-buttons">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="PrefectVotingApplicationUsers" asp-action="Index" class="hero-btn primary-btn">Vote Now</a>
                        }
                        else
                        {
                            <a asp-area="Identity" asp-page="/Account/Login" class="hero-btn primary-btn">Vote Now</a>
                        }
                        <a asp-area="Identity" asp-page="/Account/Login" class="hero-btn secondary-btn">Login</a>
                    </div>
                </div>
        </div>

        <div class="fullscreen-section section2">
        </div>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    }
    else
    {
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }

    
    
    <footer id="bottom-footer" class=" footer text-center p-3">
        <div class="container">
            &copy; 2025 - PrefectVotingApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>